permalink: pretty
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true


# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
title : "Open San Diego"
tagline: "San Diegans sharing knowledge to improve their city."
description: "We are a group of San Diegans who meet regularly to share knowledge and collaborate on projects to make our city a better place to live."
author :
  name : Open San Diego
  email : hi@opensandiego.org