version: '3.1'

services:

  jekyll:
    image: jekyll/jekyll:3.8
    ports:
      - 4000:4000
    environment:
      JEKYLL_VERSION: "3.8"
    volumes:
      - .:/srv/jekyll:delegated
    command: "jekyll serve"

